[general]
import = [
    "~/.config/alacritty/themes/themes/github_dark.toml"
]

# [font]
# size = 12.0
#

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[cursor.style]
shape = "Beam"
blinking = "On"
