# [general]
# import = [
#     "~/.config/alacritty/themes/themes/github_dark.toml"
# ]

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
size = 13.0

[cursor]
style = { shape = "Beam", blinking = "On" }

[window]
padding = { x = 10, y = 10 }
opacity = 0.90
blur = true
decorations_theme_variant = "Dark"

[mouse]
hide_when_typing = true
