window_padding_width 10

background_opacity 0.9
dynamic_background_opacity yes

font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        13

tab_bar_min_tabs    0
tab_bar_edge        top
tab_bar_style       powerline
tab_powerline_style round

window_logo_path /usr/share/icons/hicolor/scalable/apps/kitty.svg

shell /usr/bin/fish
editor /usr/bin/nano

# BEGIN_KITTY_THEME
# Catppuccin-Macchiato
include current-theme.conf
# END_KITTY_THEME
